webtalk_init -webtalk_dir C:/Users/USER/Desktop/CMPEN331_Final-Framework/CMPEN331_Final-Framework.sim/sim_1/behav/xsim/xsim.dir/TestWrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May  8 01:00:38 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "21fddfd8-1ffe-488a-be18-a4bc9f7cc691" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3a17eed8800c4043a4024ae27aab8448" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "250 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.89_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15052_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3267128158 -regid "" -xml C:/Users/USER/Desktop/CMPEN331_Final-Framework/CMPEN331_Final-Framework.sim/sim_1/behav/xsim/xsim.dir/TestWrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/USER/Desktop/CMPEN331_Final-Framework/CMPEN331_Final-Framework.sim/sim_1/behav/xsim/xsim.dir/TestWrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/USER/Desktop/CMPEN331_Final-Framework/CMPEN331_Final-Framework.sim/sim_1/behav/xsim/xsim.dir/TestWrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
